# Generated by Django 5.1.2 on 2024-10-31 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientDb',
            fields=[
                ('ingredientId', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredientName', models.CharField(max_length=50)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
