# Generated by Django 5.1.2 on 2024-10-31 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recipeDb',
            fields=[
                ('recipeId', models.IntegerField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
